import Head from 'next/head';

// Sections
import Hero from '../sections/Hero';
import SectionAbout from '../sections/SectionAbout';
import SectionProjects from '../sections/SectionProjects';

export default function Home() {
  return (
    <div className='text-slate-500'>
      <Head>
        <title>Atomic Programmers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <Hero />
      <SectionAbout />
      <SectionProjects />
    </div>
  );
}
