import Head from 'next/head';
import WorkInProgress from '../components/WorkInProgress';

const WhyUs = () => {
  return (
    <>
      <Head>
        <title>Atomic Programmers</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.svg' />
      </Head>
      <WorkInProgress />
    </>
  );
};

export default WhyUs;
